# Generated by Django 2.2 on 2020-10-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201020_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='main.User'),
        ),
    ]
